apiVersion: v1
kind: Secret
metadata:
  name: kong-admin-credentials
  namespace: kong
  labels:
    app.kubernetes.io/name: kong-deck
    app.kubernetes.io/part-of: oob-kong
 type: Opaque
stringData:
  DECK_KONG_ADDR: "http://kong-cp-kong-admin.kong.svc.cluster.local:8001"
