# ===========================================================================
# ServiceAccount for the decK sync Job
# ===========================================================================
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deck-sync-sa
  namespace: kong
  labels:
    app.kubernetes.io/name: kong-deck
    app.kubernetes.io/part-of: oob-kong
