# ==========================================================
# GLOBAL VALUES - HML
# Todas as variáveis compartilhadas ficam aqui
# ==========================================================

global:

  # --------------------------------------------------------
  # Namespace padrão
  # --------------------------------------------------------
  namespace: kong

  # --------------------------------------------------------
  # Docker Images
  # --------------------------------------------------------
  imageRegistry: 618430153747.dkr.ecr.us-east-1.amazonaws.com

  kong:
    repository: opus-open-banking-release/oob-kong
    tag: "2.35.0.17618d5-kong-3.10"

  postgres:
    repository: bitnami/postgresql
    tag: "latest"

  # --------------------------------------------------------
  # Database
  # --------------------------------------------------------
  database:
    host: postgres-kong-postgresql.kong.svc.cluster.local
    port: 5432
    name: kong
    user: kong
    password: kong
