image:
  repository: 618430153747.dkr.ecr.sa-east-1.amazonaws.com/opus-open-banking-release/oob-kong
  tag: "2.35.0.17618d5-kong-3.10"
  effectiveSemver: "3.10.0" # Força o Helm do Kong a entender a versão corretamente

env:
  role: control_plane
  database: postgres

  pg_host: postgres-kong-postgresql.kong.svc.cluster.local
  pg_port: "5432"
  pg_user: kong
  pg_password: kong
  pg_database: kong

  cluster_listen: 0.0.0.0:8005
  cluster_telemetry_listen: 0.0.0.0:8006

cluster:
  enabled: true
  tls:
    enabled: true

admin:
  enabled: true
  type: NodePort
  nodePort: 30001

proxy:
  enabled: false

ingressController:
  enabled: false
