image:
  registry: registry-1.docker.io
  repository: bitnami/postgresql
  tag: "15.6.0"

auth:
  username: kong
  password: kong
  database: kong

primary:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
