# ------------------------------------------------------------------
# Postgres Helm Values
# Usa variáveis globais
# ------------------------------------------------------------------

image:
  registry: "{{ .Values.global.postgres.registry }}"
  repository: "{{ .Values.global.postgres.repository }}"
  tag: "{{ .Values.global.postgres.tag }}"

auth:
  username: "{{ .Values.global.database.user }}"
  password: "{{ .Values.global.database.password }}"
  database: "{{ .Values.global.database.name }}"

primary:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi"
