apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-cp
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-cp
  template:
    metadata:
      labels:
        app: kong-cp
    spec:
      containers:
      - name: kong
        image: 618430153747.dkr.ecr.us-east-1.amazonaws.com/opus-open-banking-release/oob-kong:2.35.0.17618d5-kong-3.10
        env:
        - name: KONG_DATABASE
          value: "postgres"
        - name: KONG_PG_HOST
          value: "postgres-kong.kong.svc.cluster.local"
        - name: KONG_PG_PORT
          value: "5432"
        - name: KONG_PG_USER
          value: "kong"
        - name: KONG_PG_PASSWORD
          value: "kong"
        - name: KONG_PG_DATABASE
          value: "kong"
        - name: KONG_ROLE
          value: "control_plane"
        - name: KONG_CLUSTER_CERT
          value: "/etc/secrets/kong-cluster-cert/tls.crt"
        - name: KONG_CLUSTER_CERT_KEY
          value: "/etc/secrets/kong-cluster-cert/tls.key"
        ports:
        - containerPort: 8001
        - containerPort: 8005
        - containerPort: 8006
        volumeMounts:
        - name: kong-cluster-cert
          mountPath: /etc/secrets/kong-cluster-cert
          readOnly: true
      volumes:
      - name: kong-cluster-cert
        secret:
          secretName: kong-cluster-cert
---
apiVersion: v1
kind: Service
metadata:
  name: kong-cp-kong-admin
  namespace: kong
spec:
  type: NodePort
  ports:
  - port: 8001
    nodePort: 30001
    targetPort: 8001
  selector:
    app: kong-cp