apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-umbrella
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/reginaldo-opus/test-deploy.git
    targetRevision: main
    path: kong/deploy/argocd/children
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
