apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-cp
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: kong-stack
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: "*"
    helm:
      releaseName: kong-cp
      values: |
        image:
          repository: 618430153747.dkr.ecr.us-east-1.amazonaws.com/opus-open-banking-release/oob-kong
          tag: "2.35.0.17618d5-kong-3.10"
        env:
          role: control_plane
          database: postgres
          pg_host: postgres-kong-postgresql.kong.svc.cluster.local
          pg_port: "5432"
          pg_user: kong
          pg_password: kong
          pg_database: kong
          cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
          cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
          cluster_listen: 0.0.0.0:8005
          cluster_telemetry_listen: 0.0.0.0:8006
          PLUGINS: bundled,oob-error-handler,oob-fapi-interaction-id,oob-token-introspection,oob-api-event,oob-route-block,oob-mqd-event,oob-ocsp-validator,oob-operational-limits,oob-kong-consumer-handler,oob-kong-custom-metrics
          PLUGINSERVER_NAMES: oob-error-handler,oob-fapi-interaction-id,oob-token-introspection,oob-api-event,oob-route-block,oob-mqd-event,oob-ocsp-validator,oob-operational-limits
          PLUGINSERVER_OOB_ERROR_HANDLER_START_CMD: /usr/local/bin/oob-error-handler
          PLUGINSERVER_OOB_ERROR_HANDLER_QUERY_CMD: /usr/local/bin/oob-error-handler -dump
          PLUGINSERVER_OOB_ERROR_HANDLER_SOCKET: /usr/local/kong/oob-error-handler.socket
          PLUGINSERVER_OOB_FAPI_INTERACTION_ID_START_CMD: /usr/local/bin/oob-fapi-interaction-id
          PLUGINSERVER_OOB_FAPI_INTERACTION_ID_QUERY_CMD: /usr/local/bin/oob-fapi-interaction-id -dump
          PLUGINSERVER_OOB_FAPI_INTERACTION_ID_SOCKET: /usr/local/kong/oob-fapi-interaction-id.socket
          PLUGINSERVER_OOB_TOKEN_INTROSPECTION_START_CMD: /usr/local/bin/oob-token-introspection
          PLUGINSERVER_OOB_TOKEN_INTROSPECTION_QUERY_CMD: /usr/local/bin/oob-token-introspection -dump
          PLUGINSERVER_OOB_TOKEN_INTROSPECTION_SOCKET: /usr/local/kong/oob-token-introspection.socket
          PLUGINSERVER_OOB_API_EVENT_START_CMD: /usr/local/bin/oob-api-event
          PLUGINSERVER_OOB_API_EVENT_QUERY_CMD: /usr/local/bin/oob-api-event -dump
          PLUGINSERVER_OOB_API_EVENT_SOCKET: /usr/local/kong/oob-api-event.socket
          PLUGINSERVER_OOB_ROUTE_BLOCK_START_CMD: /usr/local/bin/oob-route-block
          PLUGINSERVER_OOB_ROUTE_BLOCK_QUERY_CMD: /usr/local/bin/oob-route-block -dump
          PLUGINSERVER_OOB_ROUTE_BLOCK_SOCKET: /usr/local/kong/oob-route-block.socket
          PLUGINSERVER_OOB_MQD_EVENT_START_CMD: /usr/local/bin/oob-mqd-event
          PLUGINSERVER_OOB_MQD_EVENT_QUERY_CMD: /usr/local/bin/oob-mqd-event -dump
          PLUGINSERVER_OOB_MQD_EVENT_SOCKET: /usr/local/kong/oob-mqd-event.socket
          PLUGINSERVER_OOB_OCSP_VALIDATOR_START_CMD: /usr/local/bin/oob-ocsp-validator
          PLUGINSERVER_OOB_OCSP_VALIDATOR_QUERY_CMD: /usr/local/bin/oob-ocsp-validator -dump
          PLUGINSERVER_OOB_OCSP_VALIDATOR_SOCKET: /usr/local/kong/oob-ocsp-validator.socket
          PLUGINSERVER_OOB_OPERATIONAL_LIMITS_START_CMD: /usr/local/bin/oob-operational-limits
          PLUGINSERVER_OOB_OPERATIONAL_LIMITS_QUERY_CMD: /usr/local/bin/oob-operational-limits -dump
          PLUGINSERVER_OOB_OPERATIONAL_LIMITS_SOCKET: /usr/local/kong/oob-operational-limits.socket
        secretVolumes:
          - kong-cluster-cert
        cluster:
          enabled: true
          tls:
            enabled: true
        admin:
          enabled: true
          http:
            enabled: true
            containerPort: 8001
          type: NodePort
          nodePort: 30001
        proxy:
          enabled: false
        ingressController:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m0s
