apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong-dp
  namespace: kong
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong-dp
  template:
    metadata:
      labels:
        app: kong-dp
    spec:
      containers:
      - name: kong
        image: 618430153747.dkr.ecr.us-east-1.amazonaws.com/opus-open-banking-release/oob-kong:2.35.0.17618d5-kong-3.10
        env:
        - name: KONG_DATABASE
          value: "off"
        - name: KONG_ROLE
          value: "data_plane"
        - name: KONG_CLUSTER_CONTROL_PLANE
          value: "kong-cp-kong-cluster.kong.svc.cluster.local:8005"
        - name: KONG_CLUSTER_CERT
          value: "/etc/secrets/kong-cluster-cert/tls.crt"
        - name: KONG_CLUSTER_CERT_KEY
          value: "/etc/secrets/kong-cluster-cert/tls.key"
        - name: KONG_LUA_SSL_TRUSTED_CERTIFICATE
          value: "/etc/secrets/kong-cluster-cert/tls.crt"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: kong-cluster-cert
          mountPath: /etc/secrets/kong-cluster-cert
          readOnly: true
      volumes:
      - name: kong-cluster-cert
        secret:
          secretName: kong-cluster-cert
---
apiVersion: v1
kind: Service
metadata:
  name: kong-dp-kong-proxy
  namespace: kong
spec:
  type: NodePort
  ports:
  - port: 8000
    nodePort: 30080
    targetPort: 8000
  selector:
    app: kong-dp