apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-cp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  sources:
    - repoURL: https://charts.konghq.com
      chart: kong
      targetRevision: 2.38.0
      helm:
        valueFiles:
          - $values/environments/hml/kong-cp-values.yaml

    - repoURL: https://github.com/reginaldo-opus/test-deploy.git
      targetRevision: main
      ref: values
      path: kong/poc/kong/kong-gitops

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
