apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-dp
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.konghq.com
    chart: kong
    targetRevision: 2.x.x
    helm:
      valueFiles:
        - ../../environments/hml/global-values.yaml
        - ../../environments/hml/kong-dp-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true