apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-deck-hml
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/reginaldo-opus/test-deploy.git
    targetRevision: main
    path: kong/poc/kong/kong-gitops/environments/hml/deck
  destination:
    server: https://kubernetes.default.svc
    namespace: kong
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
