apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default

  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: postgresql
      targetRevision: 18.5.7
      helm:
        valueFiles:
          # CAMINHO COMPLETO A PARTIR DA RAIZ DO GIT
          - $values/kong/poc/kong/kong-gitops/environments/hml/postgres-values.yaml

    - repoURL: https://github.com/reginaldo-opus/test-deploy.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kong

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
