apiVersion: v2
name: kong-platform
description: Kong Platform (Postgres + CP + DP)
type: application
version: 0.1.0

dependencies:
  - name: postgresql
    version: 15.5.21
    repository: https://charts.bitnami.com/bitnami

  - name: kong
    version: 2.42.0
    repository: https://charts.konghq.com
    alias: kong-cp

  - name: kong
    version: 2.42.0
    repository: https://charts.konghq.com
    alias: kong-dp
