global:
  namespace: kong
  domain: example.internal

  image:
    repository: 618430153747.dkr.ecr.sa-east-1.amazonaws.com/opus-open-banking-release/oob-kong
    tag: "2.35.0.17618d5-kong-3.10"

  postgres:
    host: postgresql
    port: 5432
    user: kong
    password: kong
    database: kong

  nodePorts:
    admin: 30001
    proxy: 30080
